version: 2.1

jobs:
    Test:
        docker:
            - image: kkiesling/dagmc_stats_depends:0.2
        steps:
            - checkout
            - run: cd tests
            - run: pytest

workflows:
    build:
        jobs:
            - Test
