version: 2.1

jobs:
    Test:
        docker:
            - image: kkiesling/dagmc_stats_depends:0.2
        steps:
            - checkout
            - run:
                working_directory: tests/
                command: pytest

workflows:
    build:
        jobs:
            - Test
