version: 2.1

jobs:
    Test:
        docker:
            - image: svalinn/dagmc-ci-ubuntu-18.04
        steps:
            - checkout
            - run: pytest

workflows:
    build:
        jobs:
            - Test
