version: 2.1

jobs:
    Test:
        docker:
            - image: kkiesling/pymoab-py3-18.04
        environment:
            PYTHONPATH: /root/project/dagmc_stats:$PYTHONPATH
        steps:
            - checkout
            - run:
                working_directory: tests/
                command: pytest

workflows:
    build:
        jobs:
            - Test
